;;; el-restish-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "el-restish" "el-restish.el" (0 0 0 0))
;;; Generated autoloads from el-restish.el

(autoload 'el-restish-get "el-restish" "\
Execute a GET request to TARGET.
With prefix argument, prompt for EXTRA-ARGS to append to the command.
With double prefix argument (C-u C-u), also toggle buffer display.

\(fn TARGET &optional EXTRA-ARGS)" t)

(autoload 'el-restish-post "el-restish" "\
Execute a POST request to TARGET.
If region is active, use it as DATA.  Otherwise prompt for data.
With prefix argument, prompt for EXTRA-ARGS to append to the command.

\(fn TARGET &optional DATA EXTRA-ARGS)" t)

(autoload 'el-restish-put "el-restish" "\
Execute a PUT request to TARGET.
If region is active, use it as DATA.  Otherwise prompt for data.
With prefix argument, prompt for EXTRA-ARGS to append to the command.

\(fn TARGET &optional DATA EXTRA-ARGS)" t)

(autoload 'el-restish-delete "el-restish" "\
Execute a DELETE request to TARGET.
With prefix argument, prompt for EXTRA-ARGS to append to the command.

\(fn TARGET &optional EXTRA-ARGS)" t)

(autoload 'el-restish-request "el-restish" "\
Execute a restish request with METHOD to TARGET.
EXTRA-ARGS is a string of additional arguments.
OPTIONS is a plist of request options.

\(fn METHOD TARGET &optional EXTRA-ARGS &rest OPTIONS)")

(autoload 'el-restish-version "el-restish" "\
Show the version of the restish executable." t)

(autoload 'el-restish-pop-response "el-restish" "\
Pop to the most recent restish response buffer." t)

;;;***

;;;### (autoloads nil "el-restish-buffer" "el-restish-buffer.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from el-restish-buffer.el

(register-definition-prefixes "el-restish-buffer" '("el-restish-"))

;;;***

;;;### (autoloads nil "el-restish-client" "el-restish-client.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from el-restish-client.el

(register-definition-prefixes "el-restish-client" '("el-restish-"))

;;;***

;;;### (autoloads nil "el-restish-config" "el-restish-config.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from el-restish-config.el

(autoload 'el-restish-config-refresh "el-restish-config" "\
Reload the restish configuration file, ignoring cache." t)

(register-definition-prefixes "el-restish-config" '("el-restish-"))

;;;***

;;;### (autoloads nil "el-restish-core" "el-restish-core.el" (0 0
;;;;;;  0 0))
;;; Generated autoloads from el-restish-core.el

(autoload 'el-restish-set-global-args "el-restish-core" "\
Set global arguments for all restish commands.
ARGS should be strings representing command-line arguments.
Example: (el-restish-set-global-args \"-f\" \"body\" \"--no-color\")
When called interactively, prompts for a string of space-separated arguments.

\(fn &rest ARGS)" t)

(autoload 'el-restish-add-global-arg "el-restish-core" "\
Add a single global argument to restish commands.
ARG should be a string representing a command-line argument.

\(fn ARG)" t)

(autoload 'el-restish-set-environment-variable "el-restish-core" "\
Set an environment variable for all restish commands.
NAME and VALUE should be strings.

\(fn NAME VALUE)" t)

(autoload 'el-restish-configure-for-body-only "el-restish-core" "\
Configure el-restish to show only response bodies (no headers).
Sets global args to include -f body and environment variable NOCOLOR=1.
Note: These are now the default settings." t)

(autoload 'el-restish-configure-full-output "el-restish-core" "\
Configure el-restish to show full HTTP responses with headers and colors.
This overrides the default body-only, no-color configuration." t)

(autoload 'el-restish-configure-no-color "el-restish-core" "\
Configure el-restish to disable colored output.
Note: This is already the default setting." t)

(autoload 'el-restish-show-configuration "el-restish-core" "\
Show current el-restish global configuration." t)

(autoload 'el-restish-enable-auto-display "el-restish-core" "\
Enable automatic display of response buffers." t)

(autoload 'el-restish-disable-auto-display "el-restish-core" "\
Disable automatic display of response buffers.

Response buffers will still be created but not displayed.
Use `el-restish-pop-response' to view the most recent response." t)

(autoload 'el-restish-toggle-auto-display "el-restish-core" "\
Toggle automatic display of response buffers." t)

(autoload 'el-restish-enable-minibuffer-preview "el-restish-core" "\
Enable minibuffer preview of responses." t)

(autoload 'el-restish-disable-minibuffer-preview "el-restish-core" "\
Disable minibuffer preview of responses." t)

(autoload 'el-restish-toggle-minibuffer-preview "el-restish-core" "\
Toggle minibuffer preview of responses." t)

(autoload 'el-restish-reset-configuration "el-restish-core" "\
Reset all el-restish global configuration to defaults." t)

(register-definition-prefixes "el-restish-core" '("el-restish-"))

;;;***

;;;### (autoloads nil "el-restish-format" "el-restish-format.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from el-restish-format.el

(register-definition-prefixes "el-restish-format" '("el-restish-"))

;;;***

;;; End of scraped data

(provide 'el-restish-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; el-restish-autoloads.el ends here
